DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name TEXT,
Bdate DATE NOT NULL,
Score INT NOT NULL
);

CREATE TABLE Orders (
UserId INT AUTO_INCREMENT PRIMARY KEY,
`Desc` TEXT,
Odate DATE NOT NULL,
Cnt INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES Users(Id)
);
CALL auto_input(10, 100, 200, 2018);